[project]
name = "empresas-python"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.7",
    "prettyconf>=2.3.0",
]

[dependency-groups]
dev = [
    "django-browser-reload>=1.21.0",
]
prod = [
    "gunicorn>=23.0.0",
]
